package npo.kib.odc_demo.core.design_system.ui.theme

import android.graphics.Color
import androidx.compose.ui.graphics.Color
//todo change light theme colors
val md_theme_light_primary = Color(0xFF00639C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCFE5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D33)
val md_theme_light_secondary = Color(0xFF006A6A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF6FF7F6)
val md_theme_light_onSecondaryContainer = Color(0xFF002020)
val md_theme_light_tertiary = Color(0xFF984061)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9E2)
val md_theme_light_onTertiaryContainer = Color(0xFF3E001D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF3FFFA)
val md_theme_light_onBackground = Color(0xFF000000)
val md_theme_light_surface = Color(0xFF00BA88)
val md_theme_light_onSurface = Color(0xFFCCFFEA)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72777F)
val md_theme_light_inverseOnSurface = Color(0xFFB7FFEC)
val md_theme_light_inverseSurface = Color(0xFF00382E)
val md_theme_light_inversePrimary = Color(0xFF98CBFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF18FFFF)
val md_theme_light_outlineVariant = Color(0xFFC2C7CF)
val md_theme_light_scrim = Color(0xFF000099)

val md_theme_dark_primary = Color(0xFF98CBFF)
val md_theme_dark_onPrimary = Color(0xFF003354)
val md_theme_dark_primaryContainer = Color(0xFF004A77)
val md_theme_dark_onPrimaryContainer = Color(0xFFCFE5FF)
val md_theme_dark_secondary = Color(0xFF4CDADA)
val md_theme_dark_onSecondary = Color(0xFF003737)
val md_theme_dark_secondaryContainer = Color(0xFF004F4F)
val md_theme_dark_onSecondaryContainer = Color(0xFF6FF7F6)
val md_theme_dark_tertiary = Color(0xFFFFB1C8)
val md_theme_dark_onTertiary = Color(0xFF5E1133)
val md_theme_dark_tertiaryContainer = Color(0xFF7B2949)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF00201A)
val md_theme_dark_onBackground = Color(0xFF79F8DC)
val md_theme_dark_surface = Color(0xFF00201A)
val md_theme_dark_onSurface = Color(0xFF79F8DC)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
val md_theme_dark_outline = Color(0xFF8C9199)
val md_theme_dark_inverseOnSurface = Color(0xFF00201A)
val md_theme_dark_inverseSurface = Color(0xFF79F8DC)
val md_theme_dark_inversePrimary = Color(0xFF00639C)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF98CBFF)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_scrim = Color(0xFF000000)


//Additional custom colors for gradient surfaces, confirm/success and cancel/error elements.
object CustomColors {
    val seed = Color(0xFF2E9BEA)
    val Gradient_Color_1 = Color(0xFF624AF2)
    val Gradient_Color_2 = Color(0xFF50DDC3)
    val Cancel_Error = Color(0xFFED2E7E)
    val Confirm_Success = Color(0xFF00BA88)
    val light_Gradient_Color_1 = Color(0xFF583DE8)
    val light_onGradient_Color_1 = Color(0xFFFFFFFF)
    val light_Gradient_Color_1Container = Color(0xFFE4DFFF)
    val light_onGradient_Color_1Container = Color(0xFF170065)
    val dark_Gradient_Color_1 = Color(0xFFC7BFFF)
    val dark_onGradient_Color_1 = Color(0xFF29009F)
    val dark_Gradient_Color_1Container = Color(0xFF3F17D0)
    val dark_onGradient_Color_1Container = Color(0xFFE4DFFF)
    val light_Gradient_Color_2 = Color(0xFF006B5C)
    val light_onGradient_Color_2 = Color(0xFFFFFFFF)
    val light_Gradient_Color_2Container = Color(0xFF70F9DE)
    val light_onGradient_Color_2Container = Color(0xFF00201B)
    val dark_Gradient_Color_2 = Color(0xFF4FDCC2)
    val dark_onGradient_Color_2 = Color(0xFF00382F)
    val dark_Gradient_Color_2Container = Color(0xFF005045)
    val dark_onGradient_Color_2Container = Color(0xFF70F9DE)
    val light_Cancel_Error = Color(0xFFBA005D)
    val light_onCancel_Error = Color(0xFFFFFFFF)
    val light_Cancel_ErrorContainer = Color(0xFFFFD9E1)
    val light_onCancel_ErrorContainer = Color(0xFF3F001B)
    val dark_Cancel_Error = Color(0xFFFFB1C5)
    val dark_onCancel_Error = Color(0xFF65002F)
    val dark_Cancel_ErrorContainer = Color(0xFF8F0045)
    val dark_onCancel_ErrorContainer = Color(0xFFFFD9E1)
    val light_Confirm_Success = Color(0xFF006C4D)
    val light_onConfirm_Success = Color(0xFFFFFFFF)
    val light_Confirm_SuccessContainer = Color(0xFF6BFBC4)
    val light_onConfirm_SuccessContainer = Color(0xFF002115)
    val dark_Confirm_Success = Color(0xFF4ADEA9)
    val dark_onConfirm_Success = Color(0xFF003827)
    val dark_Confirm_SuccessContainer = Color(0xFF005139)
    val dark_onConfirm_SuccessContainer = Color(0xFF6BFBC4)
}